build:
  maxIssues: 5

complexity:
  ComplexMethod:
    ignoreSingleWhenExpression: true

empty-blocks:
  EmptyFunctionBlock:
    active: false

exceptions:
  TooGenericExceptionCaught:
    active: false

naming:
  ConstructorParameterNaming:
    excludeClassPattern: '.*Entity$'
  PackageNaming:
    active: false

style:
  MagicNumber:
    active: false
  NewLineAtEndOfFile:
    active: false

formatting:
    active: false