[versions]
detekt = "1.22.0"
gradlePublish = "1.1.0"
gradleVersions = "0.45.0"
kotlin = "1.8.0"

[libraries]
hierynomusssh = { module = "com.hierynomus:sshj", version = "0.35.0" }
detekt-formatting = { module = "io.gitlab.arturbosch.detekt:detekt-formatting", version.ref = "detekt" }

[plugins]
gradle-publish = { id = "com.gradle.plugin-publish", version.ref = "gradlePublish" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
misc-detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
misc-gradleVersions = { id = "com.github.ben-manes.versions", version.ref = "gradleVersions" }