name: Check and Build
on:
    push:
        branches:
            - develop
    pull_request:
        branches:
            - develop
            - main

jobs:
    dependency-submission:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout sources
                uses: actions/checkout@v4
            -   name: Generate and submit dependency graph
                uses: gradle/actions/dependency-submission@v3

    detekt:
        name: Run detekt
        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v4
            -   uses: actions/setup-java@v4
                with:
                    distribution: 'zulu'
                    java-version: '17'
            -   name: Run detekt with ktlint
                run: ./gradlew detekt ktlintCheck

    build:
        name: Build
        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v4
            -   uses: actions/setup-java@v4
                with:
                    distribution: 'zulu'
                    java-version: '17'

            -   name: Test and Build
                run: ./gradlew build